# Generated by Django 4.2.2 on 2024-01-25 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b712b865-a5a9-4966-b87d-093306c3e72c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
