# Generated by Django 4.2.2 on 2024-01-26 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bee09dfd-4ad2-4efe-8638-dbef12b750da'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to='projectfiles')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbab8966-d024-4556-b67b-5e4a2572c365'), editable=False, primary_key=True, serialize=False),
        ),
    ]
