# Generated by Django 4.2.2 on 2024-01-26 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfile_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b9cc913-e6d3-4e30-bb22-31e81777038e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8fa8bf6-3b56-4678-ac9e-a1b4a98fa6a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
