# Generated by Django 4.2.2 on 2024-01-25 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e2be939-382e-49b7-a02e-e4179175a394'), editable=False, primary_key=True, serialize=False),
        ),
    ]
