# Generated by Django 4.2.2 on 2024-01-26 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89aa0724-8f35-4a36-af30-012cf12a5172'), editable=False, primary_key=True, serialize=False),
        ),
    ]
