# Generated by Django 4.2.2 on 2024-01-26 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_todolist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69ef2811-cf70-4bee-8ecc-d7312b4e83a1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
